baseURL = "https://qiti.iqc.uwaterloo.ca/"
languageCode = "en-us"
title = "QUANTUM INFORMATION WITH TRAPPED IONS"
subtitle = "University of Waterloo"
theme = "ananke"
#SectionPagesMenu = "mainmenu" #comment
[pagination]
  pagerSize = 15 # this is set low for demonstrating with dummy content. Set to a higher number. How many news items shown in one page.
summaryLength = 50

[Params]
custom_css = ["css/myStyle.css"]
background_color_class = "bg-gray"
featured_image = "images/header/Bloodstone_33_ions.jpg"
homeList = ["news", "publications"]
favicon = "images/favicon.ico"


[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[menu]

  [[menu.mainmenu]]
    name = "Research"
    identifier = "research"
    url = "#"
    weight = 10

  [[menu.mainmenu]]
    name = "Processors"
    parent = "research"
    url = "/processors/"
    weight = 11

  [[menu.mainmenu]]
    name = "Research Directions"
    parent = "research"
    url = "/research/"
    weight = 12

  [[menu.mainmenu]]
    name = "Members"
    url = "/members/"
    weight = 20

  [[menu.mainmenu]]
    name = "Publications"
    url = "/publications/"
    weight = 30

  [[menu.mainmenu]]
    name = "News"
    url = "/news/"
    weight = 40

  [[menu.mainmenu]]
    name = "Join"
    url = "/join/"
    weight = 50


[permalinks]
  news = "/news/:contentbasename/"
  publications = "/publications/:contentbasename/"
  members = "/members/:contentbasename/"

[taxonomies]
  tag = "tags"
  research_area = "research-areas"


